DROP VIEW IF EXISTS short_count_volume_session_metadata;
DROP VIEW IF EXISTS short_count_volume_session_data;
DROP TABLE IF EXISTS short_count_volume;

DROP TABLE IF EXISTS short_count_vehicle_classification ;

CREATE TABLE short_count_volume (
  rc_station                   TEXT,
  count_id                     TEXT,
  rg                           INTEGER,
  region_code                  INTEGER,
  county_code                  INTEGER,
  stat                         TEXT,
  rcsta                        TEXT,
  functional_class             INTEGER,
  factor_group                 INTEGER,
  latitude                     REAL,
  longitude                    REAL,
  specific_recorder_placement  TEXT,
  channel_notes                TEXT,
  data_type                    TEXT,
  vehicle_axle_code            INTEGER,
  year                         INTEGER,
  month                        INTEGER,
  day                          INTEGER,
  day_of_week                  TEXT,
  federal_direction            INTEGER,
  lane_code                    INTEGER,
  lanes_in_direction           INTEGER,
  collection_interval          INTEGER,
  interval_1_1                 INTEGER,
  interval_1_2                 INTEGER,
  interval_1_3                 INTEGER,
  interval_1_4                 INTEGER,
  interval_2_1                 INTEGER,
  interval_2_2                 INTEGER,
  interval_2_3                 INTEGER,
  interval_2_4                 INTEGER,
  interval_3_1                 INTEGER,
  interval_3_2                 INTEGER,
  interval_3_3                 INTEGER,
  interval_3_4                 INTEGER,
  interval_4_1                 INTEGER,
  interval_4_2                 INTEGER,
  interval_4_3                 INTEGER,
  interval_4_4                 INTEGER,
  interval_5_1                 INTEGER,
  interval_5_2                 INTEGER,
  interval_5_3                 INTEGER,
  interval_5_4                 INTEGER,
  interval_6_1                 INTEGER,
  interval_6_2                 INTEGER,
  interval_6_3                 INTEGER,
  interval_6_4                 INTEGER,
  interval_7_1                 INTEGER,
  interval_7_2                 INTEGER,
  interval_7_3                 INTEGER,
  interval_7_4                 INTEGER,
  interval_8_1                 INTEGER,
  interval_8_2                 INTEGER,
  interval_8_3                 INTEGER,
  interval_8_4                 INTEGER,
  interval_9_1                 INTEGER,
  interval_9_2                 INTEGER,
  interval_9_3                 INTEGER,
  interval_9_4                 INTEGER,
  interval_10_1                INTEGER,
  interval_10_2                INTEGER,
  interval_10_3                INTEGER,
  interval_10_4                INTEGER,
  interval_11_1                INTEGER,
  interval_11_2                INTEGER,
  interval_11_3                INTEGER,
  interval_11_4                INTEGER,
  interval_12_1                INTEGER,
  interval_12_2                INTEGER,
  interval_12_3                INTEGER,
  interval_12_4                INTEGER,
  interval_13_1                INTEGER,
  interval_13_2                INTEGER,
  interval_13_3                INTEGER,
  interval_13_4                INTEGER,
  interval_14_1                INTEGER,
  interval_14_2                INTEGER,
  interval_14_3                INTEGER,
  interval_14_4                INTEGER,
  interval_15_1                INTEGER,
  interval_15_2                INTEGER,
  interval_15_3                INTEGER,
  interval_15_4                INTEGER,
  interval_16_1                INTEGER,
  interval_16_2                INTEGER,
  interval_16_3                INTEGER,
  interval_16_4                INTEGER,
  interval_17_1                INTEGER,
  interval_17_2                INTEGER,
  interval_17_3                INTEGER,
  interval_17_4                INTEGER,
  interval_18_1                INTEGER,
  interval_18_2                INTEGER,
  interval_18_3                INTEGER,
  interval_18_4                INTEGER,
  interval_19_1                INTEGER,
  interval_19_2                INTEGER,
  interval_19_3                INTEGER,
  interval_19_4                INTEGER,
  interval_20_1                INTEGER,
  interval_20_2                INTEGER,
  interval_20_3                INTEGER,
  interval_20_4                INTEGER,
  interval_21_1                INTEGER,
  interval_21_2                INTEGER,
  interval_21_3                INTEGER,
  interval_21_4                INTEGER,
  interval_22_1                INTEGER,
  interval_22_2                INTEGER,
  interval_22_3                INTEGER,
  interval_22_4                INTEGER,
  interval_23_1                INTEGER,
  interval_23_2                INTEGER,
  interval_23_3                INTEGER,
  interval_23_4                INTEGER,
  interval_24_1                INTEGER,
  interval_24_2                INTEGER,
  interval_24_3                INTEGER,
  interval_24_4                INTEGER,
  total                        INTEGER,
  flag_field                   TEXT,
  batch_id                     TEXT
);

CREATE VIEW short_count_volume_session_metadata
  AS
    SELECT DISTINCT
        rc_station,
        count_id,
        rg,
        region_code,
        county_code,
        stat,
        rcsta,
        functional_class,
        factor_group,
        latitude,
        longitude,
        specific_recorder_placement,
        channel_notes,
        data_type,
        flag_field,
        batch_id
      FROM short_count_volume
;

CREATE VIEW short_count_volume_session_data
  AS
    SELECT
      count_id,
      vehicle_axle_code,
      year,
      month,
      day,
      day_of_week,
      federal_direction,
      lane_code,
      lanes_in_direction,
      collection_interval,
      interval_1_1,
      interval_1_2,
      interval_1_3,
      interval_1_4,
      interval_2_1,
      interval_2_2,
      interval_2_3,
      interval_2_4,
      interval_3_1,
      interval_3_2,
      interval_3_3,
      interval_3_4,
      interval_4_1,
      interval_4_2,
      interval_4_3,
      interval_4_4,
      interval_5_1,
      interval_5_2,
      interval_5_3,
      interval_5_4,
      interval_6_1,
      interval_6_2,
      interval_6_3,
      interval_6_4,
      interval_7_1,
      interval_7_2,
      interval_7_3,
      interval_7_4,
      interval_8_1,
      interval_8_2,
      interval_8_3,
      interval_8_4,
      interval_9_1,
      interval_9_2,
      interval_9_3,
      interval_9_4,
      interval_10_1,
      interval_10_2,
      interval_10_3,
      interval_10_4,
      interval_11_1,
      interval_11_2,
      interval_11_3,
      interval_11_4,
      interval_12_1,
      interval_12_2,
      interval_12_3,
      interval_12_4,
      interval_13_1,
      interval_13_2,
      interval_13_3,
      interval_13_4,
      interval_14_1,
      interval_14_2,
      interval_14_3,
      interval_14_4,
      interval_15_1,
      interval_15_2,
      interval_15_3,
      interval_15_4,
      interval_16_1,
      interval_16_2,
      interval_16_3,
      interval_16_4,
      interval_17_1,
      interval_17_2,
      interval_17_3,
      interval_17_4,
      interval_18_1,
      interval_18_2,
      interval_18_3,
      interval_18_4,
      interval_19_1,
      interval_19_2,
      interval_19_3,
      interval_19_4,
      interval_20_1,
      interval_20_2,
      interval_20_3,
      interval_20_4,
      interval_21_1,
      interval_21_2,
      interval_21_3,
      interval_21_4,
      interval_22_1,
      interval_22_2,
      interval_22_3,
      interval_22_4,
      interval_23_1,
      interval_23_2,
      interval_23_3,
      interval_23_4,
      interval_24_1,
      interval_24_2,
      interval_24_3,
      interval_24_4,
      total
    FROM short_count_volume
;


CREATE TABLE short_count_vehicle_classification (
  rc_station                   TEXT,
  count_id                     TEXT,
  rg                           INTEGER,
  region_code                  INTEGER,
  county_code                  INTEGER,
  stat                         TEXT,
  rcsta                        TEXT,
  functional_class             INTEGER,
  factor_group                 INTEGER,
  latitude                     REAL,
  longitude                    REAL,
  specific_recorder_placement  TEXT,
  channel_notes                TEXT,
  data_type                    TEXT,
  blank                        TEXT,
  year                         INTEGER,
  month                        INTEGER,
  day                          INTEGER,
  day_of_week                  TEXT,
  federal_direction            INTEGER,
  lane_code                    INTEGER,
  lanes_in_direction           INTEGER,
  collection_interval          INTEGER,
  data_interval                REAL,
  class_f1                     INTEGER,
  class_f2                     INTEGER,
  class_f3                     INTEGER,
  class_f4                     INTEGER,
  class_f5                     INTEGER,
  class_f6                     INTEGER,
  class_f7                     INTEGER,
  class_f8                     INTEGER,
  class_f9                     INTEGER,
  class_f10                    INTEGER,
  class_f11                    INTEGER,
  class_f12                    INTEGER,
  class_f13                    INTEGER,
  unclassified                 INTEGER,
  total                        INTEGER,
  flag_field                   TEXT,
  batch_id                     TEXT
);
